version: '3.3'
services:

  churchill-django:
    network_mode: host
    image: mantiby/churchill:latest
    container_name: churchill-django
    restart: always
    ports:
      - "8053:8053"
    volumes:
      - /home/manti/www/churchill.manti.by/src/:/srv/churchill/src/
      - /home/manti/www/churchill.manti.by/data/:/srv/churchill/data/
      - /home/manti/www/churchill.manti.by/log/:/var/log/churchill/
      - /home/manti/www/churchill.manti.by/static/:/srv/churchill/static/
      - /home/manti/www/churchill.manti.by/media/:/srv/churchill/media/
    environment:
      - DJANGO_SETTINGS_MODULE=churchill.settings.prod
      - EMAIL_HOST=localhost
      - EMAIL_PORT=25
