version: '3.3'
services:

  churchill-django:
    restart: always
    network_mode: host
    image: mantiby/churchill:latest
    container_name: churchill-django
    ports:
      - 8053:8053
    volumes:
      - /home/manti/www/churchill.manti.by/churchill/:/srv/churchill/src/
      - /home/manti/www/churchill.manti.by/data/:/var/lib/churchill/data/
      - /mnt/nostromo/www/churchill/static/:/var/lib/churchill/static/
      - /mnt/nostromo/www/churchill/media/:/var/lib/churchill/media/
      - /mnt/nostromo/www/churchill/log/:/var/log/churchill/
    environment:
      - DJANGO_SETTINGS_MODULE=churchill.settings.prod
    command: |
      gunicorn churchill.wsgi:application --bind 0.0.0.0:8053 --workers 2 --log-file /var/log/churchill/wsgi.log