# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShotType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='shot')),
                ('volume', models.IntegerField(default=100)),
                ('degree', models.IntegerField(default=40)),
            ],
        ),
        migrations.AddField(
            model_name='shot',
            name='type',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shots', to='shots.ShotType'),
        ),
    ]
