# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shots', '0002_auto_20161101_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shottype',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
