# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shots', '0004_shot_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shot',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
