# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 09:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shots', '0005_shot_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shot',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shots', to='shots.ShotType'),
        ),
        migrations.AlterField(
            model_name='shot',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shots', to=settings.AUTH_USER_MODEL),
        ),
    ]
