# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 09:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shots', '0007_shot_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='shottype',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shottype',
            name='deleted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shottype',
            name='user',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shot_types', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shot',
            name='user',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shottype',
            name='degree',
            field=models.IntegerField(default=40, help_text='Alcohol percentage or  '),
        ),
    ]
