# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 15:03
from __future__ import unicode_literals

import churchill.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shots', '0008_auto_20161109_0929'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShotIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=churchill.utils.image_name, verbose_name='Image')),
                ('thumb', models.ImageField(blank=True, null=True, upload_to=churchill.utils.thumb_name, verbose_name='Thumbnail')),
                ('preview', models.ImageField(blank=True, null=True, upload_to=churchill.utils.preview_name, verbose_name='Preview Image')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='shottype',
            name='image',
        ),
        migrations.RemoveField(
            model_name='shottype',
            name='preview',
        ),
        migrations.RemoveField(
            model_name='shottype',
            name='thumb',
        ),
        migrations.AddField(
            model_name='shottype',
            name='measure',
            field=models.CharField(choices=[('ml', (50, 100, 200, 330, 500, 750)), ('gr', (0.5, 1, 2, 3, 5, 10, 20)), ('pc', (1, 2, 3, 4, 5, 10, 20))], default='ml', max_length=2),
        ),
        migrations.AlterField(
            model_name='shottype',
            name='degree',
            field=models.IntegerField(default=40, help_text='Alcohol percentage or "strength"'),
        ),
        migrations.AddField(
            model_name='shottype',
            name='icon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shot_types', to='shots.ShotIcon'),
        ),
    ]
