# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shots', '0009_auto_20161111_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shottype',
            name='measure',
            field=models.CharField(choices=[('ml', 'Milliliter'), ('gr', 'Grams'), ('pc', 'Piece')], default='ml', max_length=2),
        ),
    ]
