# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shots', '0011_shottype_is_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shot',
            name='quantity',
        ),
        migrations.AddField(
            model_name='shot',
            name='volume',
            field=models.IntegerField(default=0),
        ),
    ]
