# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shots', '0012_auto_20161129_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='shottype',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
