# Generated by Django 3.1.5 on 2021-01-13 21:49

import churchill.apps.currencies.services
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("currencies", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="profile",
                        serialize=False,
                        to="auth.user",
                    ),
                ),
                ("image", models.FileField(blank=True, null=True, upload_to="profile")),
                (
                    "language",
                    models.CharField(
                        blank=True,
                        choices=[("ru-ru", "Russian"), ("en-us", "English")],
                        default="en-us",
                        max_length=5,
                    ),
                ),
                (
                    "avg_consumption",
                    models.IntegerField(
                        blank=True,
                        default=6400,
                        help_text="Average alcohol consumption in ml per year",
                    ),
                ),
                (
                    "avg_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("10"),
                        help_text="Average alcohol price for 1000 ml",
                        max_digits=5,
                    ),
                ),
                (
                    "verification_token",
                    models.CharField(blank=True, max_length=16, null=True),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        default=churchill.apps.currencies.services.get_default_currency_id,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="profiles",
                        to="currencies.currency",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
