# Generated by Django 3.1.5 on 2021-01-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="stats_calculation_strategy",
            field=models.CharField(
                choices=[
                    ("LAST_SHOT", "From the last shot"),
                    ("WEEKLY", "Weekly"),
                    ("MONTHLY", "Monthly"),
                    ("ALL_TIME", "For the all time"),
                ],
                default="MONTHLY",
                max_length=20,
            ),
        ),
    ]
