# Generated by Django 3.1.5 on 2021-03-16 14:02

from decimal import Decimal
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_profile_stats_calculation_strategy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avg_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("80"),
                help_text="Average alcohol price for 1000 ml",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
    ]
