# Generated by Django 3.1.8 on 2021-05-25 14:07

from django.conf import settings
from django.db import migrations, models

from churchill.apps.core.services import get_timezone_choices


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0004_profile_next_day_offset"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="timezone",
            field=models.CharField(
                max_length=100,
                choices=get_timezone_choices(),
                default=settings.TIME_ZONE,
            ),
        ),
    ]
