# Generated by Django 3.1.5 on 2021-01-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shots", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shot",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
