# Generated by Django 3.1.5 on 2021-01-15 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shots', '0002_shot_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShotItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('shot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shots.shot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shot_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
